{% set version = '2.1.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-remotes
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/remotes_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/remotes/remotes_{{ version }}.tar.gz
  sha256: 8944c8f6fc9f0cd0ca04d6cf1221b716eee08facef9f4b4c4d91d0346d6d68a7

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('remotes')"           # [not win]
    - "\"%R%\" -e \"library('remotes')\""  # [win]

about:
  home: https://github.com/r-lib/remotes#readme
  license: GPL (>= 2)
  summary: Download and install R packages stored in 'GitHub', 'BitBucket', or plain 'subversion'
    or 'git' repositories. This package provides the 'install_*' functions in 'devtools'.
    Indeed most of the code was copied over from 'devtools'.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: remotes
# Title: R Package Installation from Remote Repositories, Including 'GitHub'
# Version: 2.1.0
# Authors@R: c( person("Jim", "Hester", , "james.hester@rstudio.com", role = c("aut", "cre")), person("Gabor", "Csardi", , "csardi.gabor@gmail.com", role = c("aut")), person("Hadley", "Wickham", role = c("aut")), person("Winston", "Chang", role = "aut"), person("RStudio", role = "cph"), person("Martin", "Morgan", role = "aut"), person("Dan", "Tenenbaum", role = "aut"), person("Mango Solutions", role = "cph") )
# Description: Download and install R packages stored in 'GitHub', 'BitBucket', or plain 'subversion' or 'git' repositories. This package provides the 'install_*' functions in 'devtools'. Indeed most of the code was copied over from 'devtools'.
# License: GPL (>= 2)
# URL: https://github.com/r-lib/remotes#readme
# BugReports: https://github.com/r-lib/remotes/issues
# Imports: methods, stats, tools, utils
# Suggests: brew, callr, codetools, curl, covr, git2r (>= 0.23.0), knitr, mockery, pkgbuild (>= 1.0.1), pingr, rmarkdown, rprojroot, testthat, withr
# Depends: R (>= 3.0.0)
# VignetteBuilder: knitr
# RoxygenNote: 6.1.1
# SystemRequirements: Subversion for install_svn, git for install_git
# Encoding: UTF-8
# NeedsCompilation: no
# Packaged: 2019-06-24 20:53:53 UTC; jhester
# Author: Jim Hester [aut, cre], Gabor Csardi [aut], Hadley Wickham [aut], Winston Chang [aut], RStudio [cph], Martin Morgan [aut], Dan Tenenbaum [aut], Mango Solutions [cph]
# Maintainer: Jim Hester <james.hester@rstudio.com>
# Repository: CRAN
# Date/Publication: 2019-06-24 21:30:03 UTC
